---
- name: Start experiment image
  hosts: all
  vars:
    experiment_user: "{{ lookup('env','USER') }}"
    image_path: '../preparation/image.tgz'
  become: yes
  tasks:
  - name: Create target logical volume
    lvol:
      vg: "{{ lvm_vg }}"
      lv: "{{ lvm_lv }}"
      size: 20g

  - name: Unmount target partition
    mount:
      name: "{{ rootfs_dir }}"
      src:  "{{ rootfs_dev }}"
      fstype: ext4
      state: unmounted

  - name: Clear target partition
    shell: "mkfs.ext4 -q -F {{ rootfs_dev }}"
    tags:
      - image

  - name: Mount target partition
    mount:
      name: "{{ rootfs_dir }}"
      src:  "{{ rootfs_dev }}"
      fstype: ext4
      state: mounted

  - name: Remove target from fstab
    lineinfile:
      path: /etc/fstab
      regexp: '{{ rootfs_dev }}'
      state: absent

  - name: Copy image
    copy:
      src: "{{ image_path }}"
      dest: "{{ rootfs_dir }}/image.tar.gz"
    tags:
      - image

  - name: Unpack rootfs
    shell: tar xpzf "{{ rootfs_dir }}/image.tar.gz" -C "{{ rootfs_dir }}"
    args:
      warn: False
    tags:
      - image

  - name: Remove source image file
    file:
      path: "{{ rootfs_dir }}/image.tar.gz"
      state: absent
    tags:
      - image

  - name: Copy ssh host keys
    copy:
      src: "/etc/ssh/{{ item.path }}"
      dest: "{{ rootfs_dir }}/etc/ssh/{{ item.path }}"
      mode: "{{ item.mode }}"
      remote_src: yes
      force: yes
    with_items:
      - { path: "ssh_host_dsa_key", mode: "0600"}
      - { path: "ssh_host_dsa_key.pub", mode: "0644"}
      - { path: "ssh_host_ecdsa_key", mode: "0600"}
      - { path: "ssh_host_ecdsa_key.pub", mode: "0644"}
      - { path: "ssh_host_ed25519_key", mode: "0600"}
      - { path: "ssh_host_ed25519_key.pub", mode: "0644"}
      - { path: "ssh_host_rsa_key", mode: "0600"}
      - { path: "ssh_host_rsa_key.pub", mode: "0644"}

  - name: Set ssh to disable UsePAM
    lineinfile:
      path: "{{ rootfs_dir }}/etc/ssh/sshd_config"
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
    with_items:
      - { regex: "^UsePAM", line: "UsePAM yes"}
      - { regex: "^PasswordAuthentication", line: "PasswordAuthentication no"}

  - name: Change hostname
    lineinfile:
      dest: "{{ rootfs_dir }}/etc/hostname"
      regexp: '\W*'
      line: "{{ inventory_hostname }}"
      backrefs: yes

  - name: Add udev rule
    template:
      src: 70-network-ifname.rules
      dest: "{{ rootfs_dir }}/etc/udev/rules.d"
      owner: root
      group: root
      mode: 0644

  - name: Add interface configuration (legacy)
    lineinfile:
      dest: "{{ rootfs_dir }}/etc/network/interfaces"
      line: "{{ item }}"
      create: yes
    with_items:
      - "auto eth0"
      - "iface eth0 inet dhcp"

  - name: Add interface configuration (netplan)
    template:
      src: netplan.yaml
      dest: "{{ rootfs_dir }}/etc/netplan/config.yaml"
      owner: root
      group: root
      mode: 0644

  - name: Ensure /proc and /sys are in place
    file:
      path: "{{ rootfs_dir }}{{ item }}"
      state: directory
      mode: 0551
    with_items:
      - "/proc"
      - "/sys"

  - name: Add root to fstab
    lineinfile:
      dest: "{{ rootfs_dir }}/etc/fstab"
      line: "{{ rootfs_dev }} / ext4 defaults 0 1"
      regexp: '^\S+ /'

  - name: Deploy controller keys
    lineinfile:
      create: yes
      dest: "{{ rootfs_dir }}/root/.ssh/authorized_keys"
      line: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: Load experiment OS
    bootos:
      image: experiment
      reboot: yes
      kparams: "{{ kparams }}"
      experimentuser: root
    tags:
      - bootos

  - include_tasks: postinstall.yml
    vars:
      ansible_ssh_user: "root"
    tags:
      - postinstall
